package com.shimpimilan.model;

public enum FamilyActivityAction {
    PROFILE_CREATED,
    PROFILE_UPDATED,
    PHOTO_UPLOADED,
    VIDEO_UPLOADED,
    INTEREST_SENT,
    INTEREST_ACCEPTED,
    INTEREST_REJECTED,
    CHAT_MESSAGE_SENT,
    VOICE_CALL_INITIATED,
    VIDEO_CALL_INITIATED,
    PREMIUM_PURCHASED,
    GALLERY_MANAGED
}
