CREATE TABLE business_offer (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id BIGINT NOT NULL,
    title VARCHAR(100) NOT NULL,
    description TEXT NOT NULL,
    discount VARCHAR(50),
    valid_from TIMESTAMP NOT NULL,
    valid_until TIMESTAMP NOT NULL,
    banner_url VARCHAR(255),
    terms_and_conditions TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
    FOREIGN KEY (business_id) REFERENCES businesses(id)
);

ALTER TABLE businesses
    ADD COLUMN is_admin_featured BOOLEAN DEFAULT FALSE,
    ADD COLUMN priority_override INT DEFAULT 0,
    ADD COLUMN working_hours_json TEXT,
    ADD COLUMN social_links_json TEXT;
